name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: gamedev.iitk@gmail.com
        heroku_app_name: kaka-on-discord
